### ISSUE TITLE
Fix all the images in main ReadMe file

### ISSUE THREAD

**Issue by fboucher** [FBoucher/ProjectDover#23]
The links of images are broken after the refactoring in Readme.md
we should create a **medias** folder a the root level and move the related files (images) there.

**Comment by kanayo1993** [comment]
The images, Readme.md and medias folder are seemed to be good. I think there are no problems at all.
Can you explain more detail?

**Comment by fboucher** [comment]
you are right @kanayo1993 Let's close this.
